### ISSUE TITLE
postgres TEXT[] type mapped to []sql.NullString, insert fails

### ISSUE THREAD

**Issue by fho** [xo/xo#106]
I have a field in my postgreSQL table that is of type TEXT[].
Xo generates a model for it where the field is of type []sql.NullString.

When I do an insert operation on the model, I get the following error:
`sql: converting Exec argument $5 type: unsupported type []sql.NullString, a slice of struct`

It doesn't make sense to have a string array that has NULL elements.
If the type `pq.StringArray`is used instead for the field, it works.

**Comment by kenshaw** [comment]
OK -- I'll look into fixing this, but likely can't get to this today.

**Comment by fho** [comment]
@kenshaw  thanks a lot :-)

**Comment by fho** [comment]
Same problem for the`[]int16` psql database, it also get's the wrong type assigned in the generated XO code

**Comment by kenshaw** [comment]
@fho sorry I have not had time to attend to this. Could you elaborate on the issue with `[]int16`?

**Comment by fho** [comment]
@kenshaw Yes, the problem might exist for all PSQL array types that can be NULL.

If I have a field of type `integer[] NULL` in a psql table, xo is using the go type `[]sql.NullInt64` in the generated struct.
If I do an Insert Operation on the XO struct, I get the error:
`sql: converting Exec argument $11 type: unsupported type []sql.NullInt64, a slice of struct`

**Comment by stub42** [comment]
393933cfe73994e579c853f2e61bbd7ff34fdfa5 is a trivial change that fixes most of this issue for PostgreSQL, ensuring that slices are only made of the primary type rather than the nullable type. I think it fixes things for NOT NULL array types.

It does not differentiate between zero length arrays and NULL, so isn't correct for nullable array types.

**Comment by fho** [comment]
The bug is back. For an postgresql `TEXT[]` column xo generates a struct field with the wrong type `[]sql.NullString`.

@kenshaw could you reopen the ticket or should I create a new one?



I can reproduce it with the newest xo master (42b11c7999bc6ac5be620949723f44bd0ec63e02) version, also with older xo version b5c44a157d9bfa9400f34ffcc3fefa5dce9ef344 for the following  table:

```sql
create database xobugtest;
create table testtable (textarray TEXT[] null);
```

**Comment by kenshaw** [comment]
@fho apologies. Will look into it.

**Comment by fho** [comment]
@kenshaw thanks a lot

**Comment by hhhapz** [comment]
@fho does #364 solve the issue? keep in mind with this version, nil and empty slice are treated separately.

**Comment by fho** [comment]
@hhhapz yes, it does.
The generated code:
```go
// Testtable represents a row from 'public.testtable'.
type Testtable struct {
	Textarray []sql.NullString `json:"textarray"` // textarray
}
```

**Comment by hhhapz** [comment]
`sql.NullString`? It should be `pq.StringArray`

**Comment by fho** [comment]
@hhhapz ups, sorry, I copy & pasted accidentally the previous version :-)

With your branch it is:
```go
// Testtable represents a row from 'public.testtable'.
type Testtable struct {
	Textarray pq.StringArray `json:"textarray"` // textarray
}
