### ISSUE TITLE
PK only table has unset .PrimaryKey in template

### ISSUE THREAD

**Issue by stub42** [xo/xo#111]
With PostgreSQL, a table consisting of a single column that is the primary key is not getting the PrimaryKey attribute set in templates/postgres.type.go.tpl. The _exists and _deleted variables are not created and update and upsert methods can not be created.

```go
// SubnetName represents a row from 'public.subnetname'.
type SubnetName struct {
	SubnetName string `json:"subnet_name"` // subnet_name
}
```

```
# \d subnetname
   Table "public.subnetname"
   Column    | Type | Modifiers 
-------------+------+-----------
 subnet_name | text | not null
Indexes:
    "subnetname_pkey" PRIMARY KEY, btree (subnet_name)
Referenced by:
    TABLE "subnetrange" CONSTRAINT "subnetrange_subnet_name_fk" FOREIGN KEY (subnet_name) REFERENCES subnetname(subnet_name) ON DELETE CASCADE
    TABLE "subnettree" CONSTRAINT "subnettree_parent_subnet_name_fk" FOREIGN KEY (parent_subnet_name) REFERENCES subnetname(subnet_name) ON DELETE CASCADE
    TABLE "subnettree" CONSTRAINT "subnttree_child_subnet_name_fk" FOREIGN KEY (child_subnet_name) REFERENCES subnetname(subnet_name) ON DELETE CASCADE
```

**Comment by turnkey-commerce** [comment]
This is related to an issue that was solved earlier when columns other than the primary key were all ignored.  Will take a look as this looks like a variation of that one.

**Comment by turnkey-commerce** [comment]
I reproduced this and will work on a fix.  From previous experience with it there shouldn't be an upsert or update but there does need to be an insert to be able to insert a row.
