### ISSUE TITLE
--ignore-tables option

### ISSUE THREAD

**Issue by ghophp** [xo/xo#115]
hello, first of all great work with this library, it became the base for bootstrapping our projects 🥇 . we came up recently with a situation, first of all, we the `migrate` library to manage our migrations, this library uses a extra table called schema_migrations table.

is there any plans to include a option --ignore-tables in the repository? would you be interested in merging a feature like this if we implement in the library?

**Comment by hnlq715** [comment]
+1
But I prefer --include-tables (regex) style :-)
It would be helpful when we just need to generate specific tables.

**Comment by therealplato** [comment]
i'm finding the maintenance overhead and mental overhead of xo exceed its gains, so i'm attempting to incrementally phase xo out by writing new code that does not use xo. however it greedily generates code for everything which is stepping on the new code. these flags would be help me out.

more generally is xo maintained? 6 months is a long time for a stale PR
