### ISSUE TITLE
error: unknown type xmltype (oracle)

### ISSUE THREAD

**Issue by burner-account** [xo/xo#118]
Trying the very first example 
`xo oracle://<DSN> -o models`
produces 
`error: unknown type xmltype`

Is this already on some TODO-list or will this not be fixed in the near future?

(golang-1.8, InstantClient 11.2.0.4.0, sqlplus working ok)

**Comment by kenshaw** [comment]
This just needs to be added to the oracle loader. I would appreciate if you could add it (in `loaders/oracle.go`) and do testing with it. I don't know if the `ora` driver supports this type out of the box, and as I have not used this type in Oracle based schemas, I am not sure what the best way to map it to a Go type would be. My instinct would tell me that it should be similar in nature custom PostgreSQL types, and as such should probably make use of the `--custom-type-package` option.
