### ISSUE TITLE
Add comparison to sqlboiler on README.md

### ISSUE THREAD

**Issue by hugows** [xo/xo#125]
Hi,

I'd love some help to decide between this project and https://github.com/vattle/sqlboiler?

They look very similar and both seem to generate the proper models. This project generates much less code, which I find interesting...
Thanks

**Comment by natefinch** [comment]
Sqlboiler makes a very sql-like API, which is very different from the object oriented style in xo.  I vastly prefer xo's style.

**Comment by kenshaw** [comment]
It would appear that sqlboiler is "yet another query generator". `xo` generates queries based off "single source of truth" of the actual database schema. I don't know if it's really comparable, as they do two really different things.

**Comment by tooolbox** [comment]
> It would appear that sqlboiler is "yet another query generator". xo generates queries based off "single source of truth" of the actual database schema. I don't know if it's really comparable, as they do two really different things.

I know that this is from 3 years ago, but I just had to chime in that you described exactly what `sqlboiler` does.  I use it, and `xo` seems very, very similar on the surface.

> Sqlboiler makes a very sql-like API, which is very different from the object oriented style in xo. I vastly prefer xo's style.

Thanks for the comparison, good to know.  Another difference I note is it seems like `xo` has a *ton* more knobs than `sqlboiler` although I don't know that's always a good thing.
