### ISSUE TITLE
No support for nullable UUIDs in postgres

### ISSUE THREAD

**Issue by natefinch** [xo/xo#127]
UUIDs don't have code for separate types for nullable UUIDs.  This makes it impossible for code to allow the database to generate IDs for it, since you can't send in a null UUID (Also if anyone actually wanted a null UUID in a field).

**Comment by a-urth** [comment]
https://github.com/knq/xo/pull/135

**Comment by kenshaw** [comment]
The issue with this is that there is no "standard" `uuid` package that is in use everywhere. In my opinion, the way one "should" be solving this is by using a combination of custom templates and/or specifying separate custom type packages. For what it's worth, the `pq` and `pgx` packages seem to serialize to either a byte slice or a string.

I can also speak from personal experience that I've seen multiple/different encodings of UUIDs stored in the same schema, and using completely different packages in some fairly large Go projects. I would be really interested to know if there was really any kind of performance gain by using the native UUID type.

**Comment by a-urth** [comment]
Ok, but now there is already library for UUID which project relies on and there is no solve to nullable UUIDs at all.

Its better then to switch back to string in such case.
