### ISSUE TITLE
Support for not-null columns with a default

### ISSUE THREAD

**Issue by natefinch** [xo/xo#128]
Not sure how much of an edge case this is, but at work we have postgres columns that are `not null` but also have a default to generate a v4 UUID.... thus the expected behavior is that you'll insert with null and the DB will generate the ID.

It seems like if a column has a default it should be treated as nullable for writes at least, so code can let the DB set the default.  This is likely to have the somewhat unfortunate side effect of making the generated struct have a nullable column where it's only ever possible for the value to be null on insert and never again... but I don't know of any alternate way to do this.

**Comment by hugows** [comment]
I used `--ignore-fields` config to handle this in my case (`created_at` populated by a `now()` function), but something like you describe would be awesome.

(Actually I think another way `xo/xo` could work is by asking questions to the user about decisions like this, and then saving the answers in a config file. Just food for thought - I'm trying to learn about the project so I can contribute. I'm trying xo again and this time I finally got over my dislike of code generation and understand that is the proper way to do things in a language like Go...)

**Comment by turnkey-commerce** [comment]
@hugows I did a partial implementation of that on a fork of xo called [gendal ](https://github.com/turnkey-commerce/gendal) that includes a TOML config file to save those type of settings, for example: [gendal.toml](https://github.com/turnkey-commerce/gendal/blob/master/gendal.toml). It also adds the ability to exclude tables.

A wizard to set up the config file is an interesting idea, or perhaps some of the settings could be auto-generated with comments showing potential values to be used in the lists.

**Comment by hugows** [comment]
Yes, `gnorm` is great and clearly documented. I prefer the style of code `xo/xo` generates right now, but that's only a matter of adapting gnorm's templates.
