### ISSUE TITLE
support for running against a whitelist of tables

### ISSUE THREAD

**Issue by phamdt** [xo/xo#130]
i have a large db and would like to run xo for a subset of the schema since certain code bases will only care about parts of the db in my case. additionally, as tables are added i'd like to able to generate code just for the new table.

**Comment by hnlq715** [comment]
+1，maybe i could send a PR foe this？

**Comment by phamdt** [comment]
i learned from the slack channel that xo is getting a major update so might have to wait for that before any new features.

**Comment by phamdt** [comment]
sort of a duplicate of #115
