### ISSUE TITLE
Foreign key reference to another schema segfaults

### ISSUE THREAD

**Issue by stub42** [xo/xo#131]
If a PostgreSQL table contains a foreign key reference to a table in another schema, Xo will segfault.

```sql
CREATE SCHEMA auth;
CREATE SCHEMA sm;
CREATE TABLE auth.Team (
    team_id SERIAL PRIMARY KEY,
    team_name text NOT NULL UNIQUE,
    email text
);
CREATE TABLE sm.Data (
   id SERIAL PRIMARY KEY,
   owner integer NOT NULL REFERENCES auth.Team(team_id),
   data text
);
```

**Comment by natefinch** [comment]
Can you post what xo prints out?  Actual segfaults ate incredibly rare with go programs.

**Comment by stub42** [comment]
panic, SIGSEGV

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x5feb8d]

goroutine 1 [running]:
vendor/github.com/knq/xo/internal.TypeLoader.LoadTableForeignKeys(0x0, 0x0, 0x0, 0x8b26f8, 0x8b2748, 0x8b26e0, 0x8b27e0, 0x8b27d8, 0x8b27f0, 0x8b27e8, ...)
	/home/stub/src/plinth/src/vendor/github.com/knq/xo/internal/loader.go:619 +0x1fd
vendor/github.com/knq/xo/internal.TypeLoader.LoadForeignKeys(0x0, 0x0, 0x0, 0x8b26f8, 0x8b2748, 0x8b26e0, 0x8b27e0, 0x8b27d8, 0x8b27f0, 0x8b27e8, ...)
	/home/stub/src/plinth/src/vendor/github.com/knq/xo/internal/loader.go:562 +0x13b
vendor/github.com/knq/xo/internal.TypeLoader.LoadSchema(0x0, 0x0, 0x0, 0x8b26f8, 0x8b2748, 0x8b26e0, 0x8b27e0, 0x8b27d8, 0x8b27f0, 0x8b27e8, ...)
	/home/stub/src/plinth/src/vendor/github.com/knq/xo/internal/loader.go:280 +0x31a
vendor/github.com/knq/xo/internal.(*TypeLoader).LoadSchema(0xc4200a02d0, 0xc4202ee000, 0xc42012b7c0, 0xc42001df90)
	<autogenerated>:17 +0x8d
main.main()
	/home/stub/src/plinth/src/vendor/github.com/knq/xo/main.go:77 +0x4ef
exit status 2
```

**Comment by natefinch** [comment]
So, looking at the code and doing some experimenting - there's two problems here. The main one is that XO only reads a single schema right now.  So it's not importing the definitions of multiple schemas.  This is exposing a bug in the code where xo isn't checking a nil value, which causes the panic you saw.  I can fix the panic, but it still wont "work", it just will return an error like 

`error: could not find table "team" for fk data_owner_fkey in schema sm`

**Comment by stub42** [comment]
Yes, I suspected that. We can even fix the 'count not fiind table' bit, either by slurping in all tables or just relying on the foreign key definition to provide enough information to complete the code generation. The problem I can't see a backwards compatible solution for is what Go package should Xo assume the extra-schema table wrapper exists in.

The simplest way forward I see is to deprecate CLI arguments add the config file mentioned in other issues (eg. for custom type mappings). This way Xo could know when generating objects for the Foo schema where objects for the Bar schema are expected to be found.

(My current workaround was to not use database schemas in my data model, which will cause organizational issues as the project grows)

**Comment by natefinch** [comment]
It seems like the answer is to make every schema its own package. A package is a namespace, just like a schema. So you'd point xo at a directory, and it would generate directories under the root for each schema.  For databases with just a single schema, you could default to doing what we do now.
