### ISSUE TITLE
Inconsistent name in custom-query

### ISSUE THREAD

**Issue by suntong** [xo/xo#133]
This is my custom query:

```sql
SELECT
  price
FROM sales
WHERE type_id= %%type_id integer%%
  AND key = %%key string%%
```

The field `type_id` is named as `TypeID` in type `Sale` struct:

```
type Sale struct {
	SaleID   int            `json:"sale_id"`  // sale_id
	TypeID   int            `json:"type_id"`  // type_id
...
```

However, the field `type_id` is named as `Type_id` in custom query func definition:

```go
// GetPricesByType_idKey runs a custom query, returning results as GetPrice.
func GetPricesByType_idKey(db XODB, type_id integer, key string) ([]*GetPrice, error) {
```

I think, for consistency, the func definition's name should be `func GetPricesByTypeIDKey` instead. 

Please consider.

**Comment by natefinch** [comment]
That definitely seems like a valid expectation.

**Comment by kenshaw** [comment]
As a workaround, you can manually specify the name used when generating a custom query:
```sh
xo -N -T Price -F GetPrices pgsql://xodb:xodb@localhost/xodb <<ENDSQL
SELECT
  price
FROM sales
WHERE type_id= %%type_id int%%
  AND key = %%key string%%
ENDSQL
```

**Comment by suntong** [comment]
Thanks @kenshaw, I can wait, as I have the _same_ `gen` script across _different_ DBs and projects.
