### ISSUE TITLE
generate context versions of Go code in query mode

### ISSUE THREAD

**Issue by jmhodges** [xo/xo#140]
In query mode, the generated go code does not include code that uses the context versions of `database/sql`'s `DB` and `Tx` methods.

It would be very handy if they did.

**Comment by kenshaw** [comment]
Noted; xo is currently being massively rearchitected and rewritten. Please join us in the #xo channel on gophers.slack.com. I will look into seeing what can / can't be done for better integrating `context.Context` into the default templates.

**Comment by tian000** [comment]
Hello, any updates on this?
