### ISSUE TITLE
Compatibility with sqlx

### ISSUE THREAD

**Issue by andreis** [xo/xo#155]
This simple change to the `*.type.go.tpl` templates can save people who use sqlx a lot of work.

```
-	{{ .Name }} {{ retype .Type }} `json:"{{ .Col.ColumnName }}"` // {{ .Col.ColumnName }}
+	{{ .Name }} {{ retype .Type }} `json:"{{ .Col.ColumnName }}" db:"{{ .Col.ColumnName }}"` // {{ .Col.ColumnName }}

```

**Comment by joho** [comment]
I ended up copying in the xo templates to my project to take advantage of this. It makes for a great dev experience of doing all crud through xo and all adhoc querying via sqlx. I think it'd be a great idea to include it in the standard templates.

**Comment by manhdaovan** [comment]
And beyond of sqlx, it's so great if xo support custom tag in model struct field.
For example, if `--custom-tag=abc` is given by cli, like this:
```bash
xo mysql://root:@localhost/dbschema -o ./model --custom-tag=abc
```
then in the `some_model.xo.go`
```go
type SomeModel struct {
	UserID    uint64    `json:"user_id" abc:"user_id"`    // user_id
}
```
