### ISSUE TITLE
Invalid code for implicitly Notnull Primary Keys with SQlite

### ISSUE THREAD

**Issue by shful** [xo/xo#156]
An integer Primary Key column which is implicitly, but not explicitly declared as "not null" with SQlite, causes invalid code.

```
CREATE TABLE revinfo (
  rev INTEGER primary key
);
```

revinfo.xo.go generated by xo:

```
import (
	"database/sql"
	"errors"
)

// Revinfo represents a row from 'revinfo'.
type Revinfo struct {
	Rev sql.NullInt64 `json:"rev"` // rev

	// xo fields
	_exists, _deleted bool
}

// ...

// Insert inserts the Revinfo to the database.
func (r *Revinfo) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if r._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO revinfo (` +
		`` +
		`) VALUES (` +
		`` +
		`)`

	// run query
	XOLog(sqlstr)
	res, err := db.Exec(sqlstr)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	r.Rev = sql.NullInt64(id) // <<<<< Compile Error because invalid conversion
	r._exists = true

	return nil
}
```

Analogously, all Foreign Key references to the "rev" column generate the same invalid conversion in their files.

Suggestion
-----------------
XO could eventually implicitly assume Primary Keys to be "Not Null".  This should fit the SQL standard.

Disclaimer
-----------------
I'm unsure whom to blame. Eventually, the SQlite driver should report the Primary Key as "Not Null".

Notes
----------------
- Such "revinfo" tables are generated by Hibernate Envers.
- There is a historical bug in SQlite so that Primary Keys indeed can be Nullable, which does not conform to the SQL standard.
I'd find it acceptable that XO creates invalid code where SQlite allows invalid DDL :-)
But this does not apply here. The "rev" column is of type "integer" and in this special case, SQlite conforms to the SQL standard and implicitly defines the Primary Key as "Not Null".

**Comment by ichiban** [comment]
@shful I think my PR is relevant: #153
