### ISSUE TITLE
-bash: xo: command not found

### ISSUE THREAD

**Issue by ycdg** [xo/xo#162]
1. Question:
i use "xo pgsql://user:pass@host/dbname -o models", 
the terminal show that "-bash: xo: command not found".

2. What i did:
i install as "https://github.com/xo/".
`go get -u golang.org/x/tools/cmd/goimports`
`go get -u github.com/knq/xo`
no error shows.

3. The folder is as below:
- src
   - github.com
     - knq
       - xo
- pkg
  - github.com_
     - knq
        - xo
- bin
   - xo

how to fix this.

**Comment by mccolljr** [comment]
It seems like you're missing `$GOPATH/bin` in your PATH?

**Comment by mccolljr** [comment]
Add the following at the end of .bash_profile, and it should work. Your
system searches directories in the PATH variable for executables like go
and xo.

```
export PATH="$GOPATH/bin:$GOROOT/bin:$PATH"
```

Once you do that, run `source ~/.bash_profile` and you'll be good. When you
restart the terminal in the future, it will automatically take effect and
you won't need to run that line again.

**Comment by ycdg** [comment]
thank u so much, it really works.
i'd like to ask another question. 

* my GOPATH is `"/Users/myname/go"
![Uploading 屏幕快照 2018-01-19 下午10.24.55.png…]()


* myGOROOT is `"/usr/local/Cellar/go/1.9.2/libexec"`


i dont know whether i install "go" twice? should i combine them together or change the "GOPATH & GOROOT"? thank u so much
