### ISSUE TITLE
go get not working on Mac 

### ISSUE THREAD

**Issue by tiger5226** [xo/xo#166]
I was going to see  if this library would be useful for a project I am working on but I cannot even go get. I assume this has something to do with it not working with a Mac which is a shame if true. Wanted to move over from SQLBoiler to XO. 

`go get -u golang.org/x/tools/cmd/goimports`
`go get -u github.com/knq/xo`

produces the following errors in console

```
MacBook-Pro:app <user>$ go get -u golang.org/x/tools/cmd/goimports
MacBook-Pro:app <user>$ go get -u github.com/knq/xo
# github.com/mattn/go-sqlite3
sqlite3-binding.c:31162:42: error: use of undeclared identifier 'pread64'
sqlite3-binding.c:31180:42: error: use of undeclared identifier 'pwrite64'
sqlite3-binding.c:31304:22: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
sqlite3-binding.c:31313:22: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
sqlite3-binding.c:31340:20: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
sqlite3-binding.c:31357:16: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
sqlite3-binding.c:13164:38: note: expanded from macro 'ArraySize'
sqlite3-binding.c:31361:14: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
sqlite3-binding.c:13164:38: note: expanded from macro 'ArraySize'
sqlite3-binding.c:33907:11: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
sqlite3-binding.c:31166:49: note: expanded from macro 'osPread64'
sqlite3-binding.c:34019:17: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
sqlite3-binding.c:31184:57: note: expanded from macro 'osPwrite64'
```
Would be nice if developers could test out XO when the projects are developed on a mac. 

Machine: MacBook Pro (13-inch, 2017)
OS: MacOS High Sierra 10.13.3
Processor: 3.1 GHz Intel Core i5
`go version go1.9.4 darwin/amd64`

**Comment by psplabs** [comment]
I think the problem may be your machine, rather than the developers not testing on Mac. I'm using MacOS High Sierra as well, and it works perfectly for me.

**Comment by tiger5226** [comment]
As of 4/30/18 it now also works for me. I will see what the effort would be to leverage XO instead of SQLBoiler. Maybe it was a problem with the latest release, not sure.
