### ISSUE TITLE
Performing custom UPDATE queries

### ISSUE THREAD

**Issue by freb** [xo/xo#169]
Is it possible to perform `UPDATE` queries? I need to perform a simple update, but I'm getting a pq error.

```sh
xo pgsql://un:pw@localhost/test -o models -v -N -M -B -T FileVersion -F UpdateFileSetIsCurrent -a << ENDSQL
UPDATE public.file_version
SET is_current = false
WHERE file_id = %%fileID int%%
ENDSQL
```

I get the following output:

```
SQL:
CREATE TEMPORARY VIEW _xo_f0r8avpt AS (UPDATE public.file_version 
SET is_current = false 
WHERE file_id = NULL)
PARAMS:
[]

error: pq: syntax error at or near "UPDATE"
```

It's weird I'm getting a `pq` error since I can create the query manually, and it works:

```go
func UpdateFileSetIsCurrent(db XODB, fileID int) error {
	var err error

	// sql query
	const sqlstr = `UPDATE public.file_version SET (` +
		`is_current` +
		`) = ROW( ` +
		`false` +
		`) WHERE file_id = $1`

	// run query
	XOLog(sqlstr, fileID)
	_, err = db.Exec(sqlstr, fileID)
	return err
}
```

Does anyone know if `UPDATE` queries work, of if there is something simple I'm missing?

**Comment by bir** [comment]
xo uses a temporary view to determine the types and results of your custom query.  You cannot create temporary views of update statements, so you get the error you noted.  

xo does not support update statements (or upsert/insert/delete) in query mode.  The simple solution is as you noted to just build your own.

**Comment by freb** [comment]
Thanks for the confirmation on this. In practice it hasn't really been a hindrance. But the extra validation you get on custom select queries is nice.

Thanks again.
