### ISSUE TITLE
SchemaMigrationByVersion redeclared in this block

### ISSUE THREAD

**Issue by wayneashleyberry** [xo/xo#174]
```
# github.com/wayneashleyberry/xoxo/models
models/schemamigration.xo.go:118:75: SchemaMigrationByVersion redeclared in this block
	previous declaration at models/schemamigration.xo.go:92:75
```

After trying `xo` on an existing database, the models were created successfully but the generated code doesn't build.

**Comment by sw-clough** [comment]
I am experiencing this problem as well. I've just made a new Sqlite3 DB with a few tables, used this package on that database, and every model file has a duplicated function. The only difference is in the comment block, where one says `// Generated from index 'area_id_pkey'.`, and the other says `// Generated from index 'sqlite_autoindex_area_1'.`. Area is my table name in this instance. The function definition is `func AreaByID(db XODB, id int) (*Area, error) {`

**Comment by sw-clough** [comment]
Upon further investigation, I noticed the example projects used `NOT NULL PRIMARY KEY AUTOINCREMENT`, whereas my table also used `UNIQUE`. I'm guessing that caused sqlite to create an autoindex, and that autoindex wasn't handled correctly.
