### ISSUE TITLE
Ltree as field type generates an error.

### ISSUE THREAD

**Issue by afidegnum** [xo/xo#179]
Hi @kenshaw i am very grateful for this package, it has shorten my working time thousand folds.  I just encountered something this morning. 

While exploring Ltree from postgres, i have noticed an LTree field time was [generated](https://github.com/afidegnum/MyTree/blob/master/smodels/category.xo.go#L14) instead of string, there is also series of ltrees related templates which also got [generated](https://github.com/afidegnum/MyTree/tree/master/smodels). can you please through light on this?

**Comment by turnkey-commerce** [comment]
Hi @afidegnum, as far as I know there is no explicit support for LTree in xo and we would need to provide a mapping from LTree to string in the part of xo that maps those types. 

As for all of those ltree-related go files that were generated look like they come from the stored procedures that the ltree extension may have installed.
