### ISSUE TITLE
MySQL: Use with read-only account

### ISSUE THREAD

**Issue by tp** [xo/xo#182]
I am trying to use `xo` for reading from a database where I have a read-only user.

Running

```
xo mysql://user:pw@host/db-name -o models
```

results in

```
SQL:
SELECT SCHEMA()
PARAMS:
[]

error: Error 1045: Access denied for user 'user'@'ip' (using password: YES)
```

I have tried `mysqldump`, and that also fails unless I provide a  `--lock-tables=false` option, so I though maybe a similar thing is the cause here for `xo`.

(Though I am not sure if the error stems from the account's permissions or is related to something else during the initial connection.)

**Comment by turnkey-commerce** [comment]
@tp Since xo uses a URL type of syntax for connection strings (called dburl), you might want to try the following syntax to pass that option for the lock-tables. I have used a similar construct for Postgres options.

`
xo mysql://user:pw@host/db-name?lock-tables=false -o models
`

**Comment by tp** [comment]
Sorry for the late reply, could just test it now.

I get the same "access denied" error even with the parameter.

Is there another option I could set to get more verbose output (other than `-v`)? Maybe it's not (only) because of that flag.

**Comment by turnkey-commerce** [comment]
No, I don't know of any way to get more verbose output.  It's basically saying it's running "SELECT SCHEMA()" against the given credentials and failing at that.  That's the first thing it does.  

To troubleshoot further try logging in from the command line with those credentials and try to run the "SELECT SCHEMA()" directly, e.g.
```
mysql --user=user --password=pw
mysql> SELECT SCHEMA();
+------------+
| database() |
+------------+
| NULL       |
+------------+
```
SELECT SCHEMA() is just a MySQL function for getting the current database name and is equivalent to SELECT DATABASE().  If that fails the solution would be to grant execute on functions for that user.

**Comment by kenshaw** [comment]
You probably should copy the schema to a working development database that your user account can modify, to make use of `xo`. `xo` is both elegant and hacky, in that it uses underlying database magic (that requires read and write permissions on schemas) to inspect the queries. Regardless, as part of your development process you probably should not be developing against a production database.

**Comment by tp** [comment]
@turnkey-commerce Executing `SELECT SCHEMA()` works fine.

I think @kenshaw's suggestions will fix it: Copying the schema to another database and access it with a privileged user.

That resolves this then. Thanks for your help :)
