### ISSUE TITLE
[PostgreSQL] Avoid stored procedures generation for extensions

### ISSUE THREAD

**Issue by condemil** [xo/xo#188]
I tried to generate models with xo and I see that I have stored procedures for two extensions that I have enabled on database: citext and uuid-ossp. Is there a way do prevent model generation for extensions?

Here is the list of generated stored procedures:

```
sp_citext.xo.go
sp_citextcmp.xo.go
sp_citexteq.xo.go
sp_citextge.xo.go
sp_citextgt.xo.go
sp_citexthash.xo.go
sp_citextin.xo.go
sp_citextlarger.xo.go
sp_citextle.xo.go
sp_citextlt.xo.go
sp_citextne.xo.go
sp_citextout.xo.go
sp_citextpatterncmp.xo.go
sp_citextpatternge.xo.go
sp_citextpatterngt.xo.go
sp_citextpatternle.xo.go
sp_citextpatternlt.xo.go
sp_citextrecv.xo.go
sp_citextsend.xo.go
sp_citextsmaller.xo.go
sp_max.xo.go
sp_min.xo.go
sp_regexpmatch.xo.go
sp_regexpmatches.xo.go
sp_regexpreplace.xo.go
sp_regexpsplittoarray.xo.go
sp_regexpsplittotable.xo.go
sp_replace.xo.go
sp_splitpart.xo.go
sp_strpos.xo.go
sp_texticlike.xo.go
sp_texticnlike.xo.go
sp_texticregexeq.xo.go
sp_texticregexne.xo.go
sp_translate.xo.go
sp_uuidgeneratev1.xo.go
sp_uuidgeneratev1mc.xo.go
sp_uuidgeneratev3.xo.go
sp_uuidgeneratev4.xo.go
sp_uuidgeneratev5.xo.go
sp_uuidnil.xo.go
sp_uuidnsdns.xo.go
sp_uuidnsoid.xo.go
sp_uuidnsurl.xo.go
sp_uuidnsx500.xo.go
```

**Comment by david4shure** [comment]
+1

**Comment by kenshaw** [comment]
`xo` was designed around the way that I design schemas for databases. You should collect your tables/SPs/etc in a schema namespace, such as `v1` on whatever database you are using, and then use `xo` with the `--schema=` flag to specify it. For databases that don't support that (ie, MySQL), then you can use two different databases simultaneously, and prefix using the database name. Alternately, you can create custom templates to filter the names of the stored procs you don't want included in the generation.

**Comment by kenshaw** [comment]
One other thing: `xo` is meant to be a fairly high-level tool, and 100% generalized operations across all the databases aren't worth the additional implementation effort. It's fairly simple/straightforward to customize `xo` to ignore these specific SPs if that's what's called for. The way that I do this on other projects is that I version the `xo` tool into the project, with whatever changes are needed, either in custom templates, or (yes) modifying the actual Go generation logic.

I'm open to any well written PR that generalizes the ability to filter/ignore certain names from the `xo` command line, but I feel that whatever generation scripts you'd have for `xo` would be not be maintainable, as you can see in the above you have 10s of SPs that you want to ignore. This is a _organizational_ problem and a _maintenance_ problem. Even if `xo` had a general purpose `--ignore=` flag, it would not be advisable to have a call to the `xo` tool with 10s of `--ignore=` flags.
