### ISSUE TITLE
Using same query argument in multiple places

### ISSUE THREAD

**Issue by jszwedko** [xo/xo#189]
Is there a pattern for generating queries that allow you to specify the same variable multiple places in the query?

I was hoping to be able to do something like:

```
SELECT
  "id"
FROM
  "foo"
WHERE
  %%id *int64%% = NULL OR "foo"."id" = %%id%% AND
  %%slug *string%% = NULL OR "foo"."slug" = %%slug%%
```

But the query parser expects each placeholder to be unique and to include a type.

I'd like to use this pattern to search by multiple optional fields.

The closest I've gotten is:

```
SELECT
  "id"
FROM
  "foo"
WHERE
  %%id *int64%% = NULL OR "foo"."id" = %%id *int64%% AND
  %%slug *string%% = NULL OR "foo"."slug" =  %%slug *string%% 
```

But this generates a method signature that requires you to pass the same argument multiple times:

```
func FooByIdIdSlugSlug(db XODB, id *int64, id *int64, slug *string, slug *string) (*Foo, error)
```

**Comment by kenshaw** [comment]
I'm open to accepting a pull request that detects this, and collapses the variables, however I would suggest that the simple workaround here would be to name each parameter separately, and to just pass a copy. 

I would like to point out that ` %%id *int64%% = NULL` is injecting a column name. Unless your column names are numbers, I doubt this query is going to do what you expect it to do.

On a separate note, is there a reason you're using pointers in custom query parameters? While that's a perfectly valid use with `xo`, I wouldn't have ever thought of doing that -- to me it seems ambiguous both from Go and SQL perspectives.

**Comment by jszwedko** [comment]
@kenshaw thanks for taking a look!

A realize the query shape is a bit odd, but my goal is essentially to allow one query to be used to query along multiple, optional, parameters.

I realized the query needed to be adjusted slightly:

```sql
SELECT
  "id"
FROM
  "foo"
WHERE
  (%%id *int64%% IS NULL OR "foo"."id" = %%id%%) AND
  (%%slug *string%% IS NULL OR "foo"."slug" = %%slug%%)
```

With `IS NULL` instead of `= NULL` and `()` to group precedence.

This allows you to pass either `id` and/or `slug` and get records that match. If you pass `null` for one of them, it will skip that condition (which is also why I'm using pointer values for the parameters; I believe I could have also used `sql.NullX`).

For example, a populated query might look like:

```sql
SELECT
  "id"
FROM
  "foo"
WHERE
  (NULL IS NULL OR "foo"."id" = NULL) AND
  ("something" IS NULL OR "foo"."slug" = "something")
```

Where only `slug` was passed.

Right now I'm working around this by passing additional boolean parameters for each actual parameters informing the query whether to use that condition:

```sql
SELECT
  "id"
FROM
  "foo"
WHERE
  (%%searchById boo %% = TRUE OR "foo"."id" = %%id int64%%) AND
  (%%searchBySlug bool%% = TRUE OR "foo"."slug" = %%slug string%%)
```

Notably the example of id/slug isn't the best, but you could imagine a similar case where you want to expose a general search method to the user without generating N queries with permutations of the `WHERE` clause (e.g. maybe we want to let them search by name and/or description of some field).

**Comment by jszwedko** [comment]
The workaround of naming them differently and passing a copy is definitely possible too.

**Comment by kenshaw** [comment]
Yes, I immediately grokked that whatever database you're working with was likely going to convert a `nil` pointer to `NULL`. Personally, I would have detected that in advance, and used a separate query, since it's confusing to a database developer, and has no net effect (other than possibly more parsing time on behalf of the database). It's just not the best example of SQL where you might want to use the same variable twice in a query.

Anyway, while I don't feel it's an absolute necessity, I'm happy to merge a well written PR that analyzes the variable names and generates a func with only the one parameter. You might find that's quite difficult to actually implement, however, using the existing Go template syntax.

**Comment by jszwedko** [comment]
:+1: I'll take a shot when I get some time.

My concern with detecting it in advance and using a separate query is that you end up needing to have `2 ^ n` (I believe) queries to encompass `n` searchable fields. Perhaps I could get `xo` to generate those though.

**Comment by kenshaw** [comment]
Just change it from a slice of parameters, to a map.

**Comment by jszwedko** [comment]
Hmm, you mean if I were building the query? I have considered just doing query building for these sorts of queries rather than generation.
