### ISSUE TITLE
aggregates are always strings?

### ISSUE THREAD

**Issue by cschep** [xo/xo#197]
Hello, me again!

I've written a query with group by and a few aggregate functions, AVG and SUM, and they are being generated as strings in their return types. Curious why? Their underlying types are REAL and INT. 

Thanks for any help!

**Comment by kenshaw** [comment]
What database? Can you show the full query? If this is an issue, do a force type. Not all the database's introspection queries are capable of returning the types in a custom query.

**Comment by cschep** [comment]
Wow, Sorry I never responded. This makes sense, will close!
