### ISSUE TITLE
Preventing schema references from being added to sql consts

### ISSUE THREAD

**Issue by arran4** [xo/xo#198]
I am using sqlite for testing but mysql in development. However when I generate off the MySQL instance it stores the full schema name and I can't figure out how to turn this functionality off.

I get:
```
	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO "db1"."table1" (` +
		`...` +
		`) VALUES (` +
		`?, ?, ?, ?, ?` +
		`)`

```

When I would like:
```
	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO "table1" (` +
		`...` +
		`) VALUES (` +
		`?, ?, ?, ?, ?` +
		`)`

```

**Comment by otofune** [comment]
I think schema names are often different between production or development environment.
This functionally is nice for that case.

I'm waiting and currently using workaround with (GNU) sed.

**Comment by arran4** [comment]
Ah wow. This is quite old. Yeah I don't think the ability should be removed I can see it been vital however it should be togglable or, at least database engine aware.
