### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by clearcodecn** [xo/xo#199]
☁  better-framework  go get -u github.com/xo/xo                
go: finding github.com/xo/xo latest
go: finding github.com/xo/dburl latest
go: finding golang.org/x/sync latest
go: finding github.com/xo/xoutil latest
go: finding golang.org/x/net latest
go: finding github.com/knq/snaker latest
go: finding github.com/denisenkom/go-mssqldb latest
go: finding github.com/google/pprof latest
go: finding golang.org/x/lint latest
go: finding golang.org/x/time latest
go: finding google.golang.org/genproto latest
go: finding gopkg.in/check.v1 latest
go: finding honnef.co/go/tools latest
go: finding golang.org/x/oauth2 latest
go: finding github.com/gedex/inflector latest
go: finding github.com/golang/glog latest
go: finding github.com/beorn7/perks latest
go: finding golang.org/x/build latest
go: finding golang.org/x/tools latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/perf latest
go: finding github.com/jellevandenhooff/dkim latest
go: finding github.com/flynn/go-shlex latest
go: finding github.com/jstemmer/go-junit-report latest
go: finding github.com/tarm/serial latest
go: finding github.com/google/btree latest
go: finding github.com/prometheus/procfs latest
go: finding golang.org/x/crypto latest
go: finding github.com/prometheus/client_model latest
go: finding go4.org latest
go: finding github.com/bradfitz/go-smtpd latest
go: finding github.com/gonum/internal latest
go: finding github.com/gregjones/httpcache latest
go: finding github.com/gonum/floats latest
go: finding github.com/aclements/go-gg latest
go: finding github.com/aclements/go-moremath latest
go: finding golang.org/x/exp latest
go: finding github.com/coreos/go-systemd latest
go: finding grpc.go4.org latest
go: finding github.com/gonum/blas latest
go: finding github.com/gonum/matrix latest
go: finding github.com/alecthomas/units latest
go: finding github.com/alecthomas/template latest
go: finding github.com/eapache/go-xerial-snappy latest
go: finding github.com/golang/lint latest
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
go: finding golang.org/x/mobile latest
go: finding gopkg.in/tomb.v1 latest
go get: error loading module requirements
☁  better-framework  go get -u github.com/xo/xo
go: finding github.com/xo/xo latest
go: finding github.com/xo/xoutil latest
go: finding github.com/xo/dburl latest
go: finding golang.org/x/net latest
go: finding github.com/knq/snaker latest
go: finding golang.org/x/crypto latest
go: finding golang.org/x/tools latest
go: finding golang.org/x/time latest
go: finding golang.org/x/oauth2 latest
go: finding github.com/denisenkom/go-mssqldb latest
go: finding github.com/beorn7/perks latest
go: finding golang.org/x/lint latest
go: finding golang.org/x/sync latest
go: finding github.com/prometheus/procfs latest
go: finding gopkg.in/check.v1 latest
go: finding github.com/eapache/go-xerial-snappy latest
go: finding golang.org/x/build latest
go: finding github.com/bradfitz/go-smtpd latest
go: finding golang.org/x/perf latest
go: finding github.com/google/btree latest
go: finding honnef.co/go/tools latest
go: finding grpc.go4.org latest
go: finding google.golang.org/genproto latest
go: finding github.com/golang/glog latest
go: finding go4.org latest
go: finding github.com/coreos/go-systemd latest
go: finding github.com/jstemmer/go-junit-report latest
go: finding github.com/flynn/go-shlex latest
go: finding github.com/gedex/inflector latest
go: finding golang.org/x/sys latest
go: finding github.com/gregjones/httpcache latest
go: finding github.com/tarm/serial latest
go: finding golang.org/x/exp latest
go: finding github.com/prometheus/client_model latest
go: finding github.com/aclements/go-gg latest
go: finding github.com/golang/lint latest
go: finding github.com/mwitkow/go-conntrack latest
go: finding github.com/gonum/blas latest
go: finding github.com/GoogleCloudPlatform/cloudsql-proxy latest
go: finding golang.org/x/tools v0.0.0-20181030221726-6c7e314b6563
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
go: finding gopkg.in/tomb.v1 latest
go: finding github.com/rcrowley/go-metrics latest
go: finding github.com/gonum/internal latest
go get: error loading module requirements

**Comment by BenKnigge** [comment]
Same issue. It looks like this is happening in several different go repos using modules. 

see also https://github.com/golang/lint/issues/436

You may need to update the dependencies in xo to resolve this.

**Comment by Notargets** [comment]
This is what I get:
```
$ go get -u github.com/xo/xo
go: finding github.com/xo/xo latest
go: finding golang.org/x/sync latest
go: finding github.com/gedex/inflector latest
go: finding github.com/xo/xoutil latest
go: finding github.com/denisenkom/go-mssqldb latest
go: finding golang.org/x/net latest
go: finding github.com/knq/snaker latest
go: finding golang.org/x/crypto latest
go: finding github.com/xo/dburl latest
go: finding gopkg.in/check.v1 latest
go: finding github.com/jstemmer/go-junit-report latest
go: finding golang.org/x/oauth2 latest
go: finding golang.org/x/exp latest
go: finding golang.org/x/lint latest
go: finding google.golang.org/genproto latest
go: finding golang.org/x/sys latest
go: finding honnef.co/go/tools latest
go: finding golang.org/x/tools latest
go: finding golang.org/x/time latest
go: finding github.com/google/pprof latest
go: finding github.com/golang/glog latest
go: finding github.com/BurntSushi/xgb latest
go: finding github.com/prometheus/procfs latest
go: finding golang.org/x/image latest
go: finding github.com/eapache/go-xerial-snappy latest
go: finding golang.org/x/mobile latest
go: finding github.com/rcrowley/go-metrics latest
go: finding github.com/prometheus/client_model latest
go: finding github.com/kr/logfmt latest
go: finding github.com/mwitkow/go-conntrack latest
go: finding github.com/xdg/scram latest
go: finding gopkg.in/tomb.v1 latest
go: finding github.com/alecthomas/units latest
go: finding github.com/alecthomas/template latest
go build github.com/denisenkom/go-mssqldb/internal/cp: module requires Go 1.12
```
