### ISSUE TITLE
xo sigfaults when foreign key references to a non existing table

### ISSUE THREAD

**Issue by bodemann** [xo/xo#233]
Tested on SQLite

This works
foreign key(tag_id)			references tags(id)

This sigfautls
foreign key(tag_id)			references tagX(id)

when the tagX table does not exists.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x62d060]

goroutine 1 [running]:
github.com/xo/xo/internal.TypeLoader.LoadTableForeignKeys(0x94c3b0, 0x94c3b8, 0x0, 0x94c370, 0x0, 0x94c360, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jb/go/pkg/mod/github.com/xo/xo@v0.0.0-20200425011923-7818603ff52b/internal/loader.go:616 +0x220
github.com/xo/xo/internal.TypeLoader.LoadForeignKeys(0x94c3b0, 0x94c3b8, 0x0, 0x94c370, 0x0, 0x94c360, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jb/go/pkg/mod/github.com/xo/xo@v0.0.0-20200425011923-7818603ff52b/internal/loader.go:559 +0x133
github.com/xo/xo/internal.TypeLoader.LoadSchema(0x94c3b0, 0x94c3b8, 0x0, 0x94c370, 0x0, 0x94c360, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jb/go/pkg/mod/github.com/xo/xo@v0.0.0-20200425011923-7818603ff52b/internal/loader.go:280 +0x2fb
main.main()
	/home/jb/go/pkg/mod/github.com/xo/xo@v0.0.0-20200425011923-7818603ff52b/main.go:77 +0x47a

**Comment by beiriannydd** [comment]
Yep I noticed that too when I broke a schema recently.

**Comment by nmiculinic** [comment]
btw, This seems similar to #235

**Comment by beiriannydd** [comment]
It's probably useful to mention what behavior we would like.  I think it would be best if instead of segfaulting, it would display "schema error on line nnn: "foreign key(tag_id) references tagX(id)" : table tagX doesn't exist"
