### ISSUE TITLE
nullable value in geting procs list by pg_get_function_result

### ISSUE THREAD

**Issue by mr-tron** [xo/xo#234]
```
SQL:
SELECT p.proname, pg_get_function_result(p.oid) FROM pg_proc p JOIN ONLY pg_namespace n ON p.pronamespace = n.oid WHERE n.nspname = $1
PARAMS:
[my_scheme]

error: sql: Scan error on column index 1, name "pg_get_function_result": converting NULL to string is unsupported
```

![image](https://user-images.githubusercontent.com/702560/99274773-c5b3ab80-283b-11eb-92ae-1dc90504a39d.png)

and example of procedure
```
create procedure employee_wbuser_upd(_employee_id integer, _wbuser_id bigint)
    language plpgsql
as
$$
```

**Comment by breml** [comment]
I have the same issue while working with TimescaleDB flavor of PostgreSQL.

I added a small workaround, which fixed the problem for now. I changed line https://github.com/xo/xo/blob/master/models/proc.xo.go#L19 to:

```none
coalesce(pg_get_function_result(p.oid), 'void')
```
