### ISSUE TITLE
Install failed / xoutil missing

### ISSUE THREAD

**Issue by temparus** [xo/xo#242]
Installing with `go get -u github.com/xo/xo` currently fails with the following output:

```shell
Cloning into '/go/src/github.com/xo/xoutil'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/xo/xoutil: exit status 128
```

The repository `xo/xoutil` does not seem to exist anymore.

When did that go missing?

**Comment by LeviMatus** [comment]
Any updates on this?

**Comment by temparus** [comment]
Someone uploaded it again to GitHub. If you are using Go Modules, you can add a `replace` statement for that package as a workaround.

https://github.com/AstroProfundis/xoutil

**Comment by temparus** [comment]
The installation seems to work with golang version 1.16 just fine, but fails with older versions.
