### ISSUE TITLE
Stored procedures with same names results in malformed output

### ISSUE THREAD

**Issue by captain-refactor** [xo/xo#278]
Hello,

I was experimenting with xo and found this bug, when there are multiple stored procedures with the same name.

## Prerequisites

DBMS: PostgreSQL (ver. 13.3 (Debian 13.3-1.pgdg100+1))
Xo version: v0.0.0-20210714011506-76d862ce7b33
Go version:  go1.16.4 windows/amd64

```sql
drop schema if exists sandbox CASCADE;
create schema sandbox;
SET search_path = sandbox;

create table users
(
    id        uuid default gen_random_uuid() not null
        constraint users_pk
            primary key,
    name      text                           not null,
    surname   text,
    something integer
);

create procedure create_user(_name text)
    language plpgsql
as
$$
begin
    insert into sandbox.users (name)
    values (_name);
end;
$$;

create procedure create_user(_name text, _surname text)
    language plpgsql
as
$$
begin
    insert into sandbox.users (name, surname)
    values (_name, _surname);
end;
$$;
```

## Command
` xo schema -s sandbox pgsql://postgres@localhost:30702/sandbox?sslmode=disable `

## Result
```go
package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// CreateUser calls the stored procedure 'sandbox.create_user(text, text, text, text, text, text) (void, void, void, void)' on db.
func CreateUser(ctx context.Context, db DB, name, name, surname, name, name, surname string) (Void, Void, Void, Void, error) {
	// call sandbox.create_user
	const sqlstr = `CALL sandbox.create_user($1, $2, $3, $4, $5, $6)`
	// run
	var r0 Void
	var r1 Void
	var r2 Void
	var r3 Void
	logf(sqlstr, name, name, surname, name, name, surname)
	if err := db.QueryRowContext(ctx, sqlstr, name, name, surname, name, name, surname).Scan(&r0, &r1, &r2, &r3); err != nil {
		return Void{}, Void{}, Void{}, Void{}, logerror(err)
	}
	return r0, r1, r2, r3, nil
}
```

There is one invalid function in output.

## Expectation

I would expect, that when there are multiple procedures with the same name, they will get suffix with parameters.
```go
func CreateUserByName(ctx context.Context, db DB, name string) { ... }
func CreateUserByNameAndSurname(ctx context.Context, db DB, name string, surname string) { ... }
```

**Comment by hhhapz** [comment]
Hi! Thank you for using XO. I can take a look at how postgres works with differentiating overloaded functions within introspection tables, however this is not the biggest priority at the moment and from experience of implementing procs a couple days back, the postgres introspection tables are a bit tough to work with. I'll keep you updated.

**Comment by hhhapz** [comment]
Does this correctly work if the procs have different names? @captain-refactor

**Comment by kenshaw** [comment]
This would require quite a bit of reworking of the introspection queries. I agree that `xo` in principle should support this, and I'll endeavor to fix it, but I don't think this should be a high priority. In my opinion (and no offense meant here), I feel this schema design is "incorrect".

The way to correct/remedy this would be to rename the second stored procedure to `create_user_with_name`, as this will more correctly express the intent of the second stored procedure. 

In my opinion, the way to design a Go model package for a database would be to have a 1:1 mapping of a `func` to a stored procedure, and they should have canonicalized/idiomatic identifier to name mapping. Specifically, it should be a `CamelCase` Go identifier to a database `snake_case` name. Since Go (and many other programming languages) do not allow overloading function names, it seems clear here the right approach would be to rename the second stored proc. While it may make sense in some programming languages (such as Java) that allow overloading function names, I find that for most programming language/database combinations that this is not what `xo` should do.

**Comment by captain-refactor** [comment]
@hhhapz When procs names are different, then it works as expected.

@kenshaw That schema design was at least questionable for sure. You are right, that the ideal solution is to change procedures name. 
I was thinking about situations, when database schema is out of developers control. (legacy database, database managed by another team)
Another solution would be to use procedure `oid` value as a suffix, only when procedures names collision occurs. That would be an ugly solution for an ugly scheme, but it would be working.

I will try to look into fixing it too

**Comment by kenshaw** [comment]
I agree; we will fix this in due course. I would like `xo` to support all possible schemas, and this is definitely a bug/error, and we very much appreciate you finding it. We'll resolve to get it fixed, but I don't have a specific ETA at the moment, as we're busy working on other more functional improvements that will drastically make `xo` a better tool. In the interim, if you have a schema like that, I'd consider just erasing the generated code and/or simply not using the code generated.

**Comment by hhhapz** [comment]
> I was thinking about situations, when database schema is out of developers control. (legacy database, database managed by another team)

I will be adding support for name name collisions that will then suffix the field names. ETA should be a few days. 👍🏽

**Comment by hhhapz** [comment]
Hey, overloaded procs and functions should be working now, @captain-refactor. If not, let me know. There has also been an example added to The a_bit_of_everything schema. Functions and procedures that have conflicting names should be generated with `[Name]By[Param][Param]And[Param]`. Your two procedures should be generated as `CreateUserByName` and `CreateUserByNameAndSurname`.
