### ISSUE TITLE
xo forcing lower case for models now?

### ISSUE THREAD

**Issue by suntong** [xo/xo#281]
Previously, when I named my models as 

`xo -o xoMyMod ...`

It'll created all .go files under `xoMyMod` with 

`package xoMyMod`

But now the `package` are named `xomymod` (while still under the `xoMyMod` folder). 

Is it by design or overlooked?

**Comment by kenshaw** [comment]
This was not intentional, and has been fixed. Thanks for finding this. However, I would like to point out that idiomatically, Go package names should be all lower case.

**Comment by suntong** [comment]
Oh, Thanks!
