### ISSUE TITLE
Syntax error of generated sqlite3 .dot digraph

### ISSUE THREAD

**Issue by suntong** [xo/xo#282]
I save the content of
https://raw.githubusercontent.com/xo/xo/master/_examples/booktest/sqlite3.xo.dot
as /tmp/booktest-sqlite3.dot

but cannot process it with dot:

```
$ dot /tmp/booktest-sqlite3.dot
Error: /tmp/booktest-sqlite3.dot: syntax error in line 2 near '.'

$ dotty /tmp/booktest-sqlite3.dot
graph parser: syntax error near line 2
context:  >>> .oktestbooktest. <<< db {
dotty.lefty: cannot load graph
```

The `oracle.xo.dot` appears to be fine.

**Comment by kenshaw** [comment]
Commit 313d7ff35019f0fd1e579b754aa5648d410e4ad5 fixes this.
