### ISSUE TITLE
[Wish] Support REFERENCES through ALTER TABLE please

### ISSUE THREAD

**Issue by suntong** [xo/xo#283]
There are two ways `REFERENCES` are defined, one is within `CREATE TABLE` itself, the other is after `CREATE TABLE`, via `ALTER TABLE`. 

I'm wishing REFERENCES through ALTER TABLE will be supported some time, as both the MS-Sql and the db schema designing tools that I'm using are doing it this way. 

Here is an example:

<details>

<summary>example</summary>

```sql
CREATE TABLE "Customer" (
    "CustomerID" int   NOT NULL,
    "Name" string   NOT NULL,
    "Address1" string   NOT NULL,
    "Address2" string   NULL,
    "Address3" string   NULL,
    CONSTRAINT "pk_Customer" PRIMARY KEY (
        "CustomerID"
     )
);

CREATE TABLE "Order" (
    "OrderID" int   NOT NULL,
    "CustomerID" int   NOT NULL,
    "TotalAmount" money   NOT NULL,
    "OrderStatusID" int   NOT NULL,
    CONSTRAINT "pk_Order" PRIMARY KEY (
        "OrderID"
     )
);

CREATE TABLE "OrderLine" (
    "OrderLineID" int   NOT NULL,
    "OrderID" int   NOT NULL,
    "ProductID" int   NOT NULL,
    "Quantity" int   NOT NULL,
    CONSTRAINT "pk_OrderLine" PRIMARY KEY (
        "OrderLineID"
     )
);

-- Table documentation comment 1 (try the PDF/RTF export)
-- Table documentation comment 2
CREATE TABLE "Product" (
    "ProductID" int   NOT NULL,
    -- Field documentation comment 1
    -- Field documentation comment 2
    -- Field documentation comment 3
    "Name" varchar(200)   NOT NULL,
    "Price" money   NOT NULL,
    CONSTRAINT "pk_Product" PRIMARY KEY (
        "ProductID"
     ),
    CONSTRAINT "uc_Product_Name" UNIQUE (
        "Name"
    )
);

CREATE TABLE "OrderStatus" (
    "OrderStatusID" int   NOT NULL,
    "Name" string   NOT NULL,
    CONSTRAINT "pk_OrderStatus" PRIMARY KEY (
        "OrderStatusID"
     ),
    CONSTRAINT "uc_OrderStatus_Name" UNIQUE (
        "Name"
    )
);

ALTER TABLE "Order" ADD CONSTRAINT "fk_Order_CustomerID" FOREIGN KEY("CustomerID")
REFERENCES "Customer" ("CustomerID");

ALTER TABLE "Order" ADD CONSTRAINT "fk_Order_OrderStatusID" FOREIGN KEY("OrderStatusID")
REFERENCES "OrderStatus" ("OrderStatusID");

ALTER TABLE "OrderLine" ADD CONSTRAINT "fk_OrderLine_OrderID" FOREIGN KEY("OrderID")
REFERENCES "Order" ("OrderID");

ALTER TABLE "OrderLine" ADD CONSTRAINT "fk_OrderLine_ProductID" FOREIGN KEY("ProductID")
REFERENCES "Product" ("ProductID");

CREATE INDEX "idx_Customer_Name"
ON "Customer" ("Name");
```

</details>

The generated .dot digraph will be missing the relations between them, which is supposed to be:

![image](https://user-images.githubusercontent.com/422244/125840183-7b6ee423-98f3-42f1-b35c-9f117e562550.png)

**Comment by kenshaw** [comment]
@suntong I'm not sure what you mean here. Do you mean that columns later added by `ALTER` are not being picked up by `xo`? Could you provide a simple test schema that demonstrates this?

**Comment by kenshaw** [comment]
@suntong We used your example schema with the latest version of `xo` and we believe it generated the correct definitions for every database index and constraint. Can you please give more details of what, in your opinion, is missing?

Attached is the generated files from `xo`.
[schema.zip](https://github.com/xo/xo/files/6827277/schema.zip)

**Comment by suntong** [comment]
Hmm.. I was talking about the generated .dot digraph. Here is what it looks like with the booktest example:

![image](https://user-images.githubusercontent.com/422244/125969541-cc54944f-0967-4575-9cb6-021bb5188eb9.png)

I.e., the tables are _**linked**_, with relations between them. while for me the generated .dot digraph does not have any links/relations between the tables. Maybe it is not the problem of DB but the `.dot` digraph generation itself. Sorry I didn't make it clear before.

Can you post the generated `.dot` digraph of the above sql in OP  from your side please?

**Comment by kenshaw** [comment]
I ran `xo` against the schema and have attached the files here. Foreign keys are represented by the lines between tables. We will likely clean up the dot templates, and add more information later. In the interim, it's possible to create/modify the dot template.

![sqlserver](https://user-images.githubusercontent.com/2274859/126004037-b88263fc-71bb-4f0d-879d-a44756e9da49.png)
[sqlserver.zip](https://github.com/xo/xo/files/6833169/sqlserver.zip)

**Comment by suntong** [comment]
Thanks for the reply.

In my view, 

- the `booktest` example defines REFERENCES within `CREATE TABLE` itself, thus, the tables are linked, with relations between them.
- the above sql in OP defines REFERENCES after `CREATE TABLE`, via `ALTER TABLE`, thus, the generated .dot digraph does not have any links/relations between the tables.

Wishing someday the above sql in OP will have links/relations between the tables too.

Thanks

**Comment by hhhapz** [comment]
Hey @suntong please double check your schema because they are indeed included. You can see them in the zip @kenshaw sent yesterday too. Can you show what output you are getting? 

Here is the download link for the schema you provided in you first message once more:  [Your schema result](https://github.com/xo/xo/files/6827277/schema.zip)

**Comment by suntong** [comment]
Sorry @hhhapz, I don't know why I didn't get message from github of your reply.

Please note, the schema I provided in OP is about `Customer`, `Order`, etc.

I don't know why you both keep referring back to booktest, which I've repeatedly mention it being working fine.

> Thanks for the reply.
> 
> In my view,
> 
> * the `booktest` example defines REFERENCES within `CREATE TABLE` itself, thus, the tables are linked, with relations between them.
> * the above sql in OP defines REFERENCES after `CREATE TABLE`, via `ALTER TABLE`, thus, the generated .dot digraph does not have any links/relations between the tables.
> 
> Wishing someday the above sql in OP will have links/relations between the tables too.
> 
> Thanks

And now my issue is just being closed without being addressed.

**Comment by hhhapz** [comment]
![image](https://user-images.githubusercontent.com/29532600/126884484-60351176-7134-4ee7-a942-0749a643199a.png)

![image](https://user-images.githubusercontent.com/29532600/126884497-9cfb1136-6cd4-422b-985e-3febb92559a7.png)

**Comment by hhhapz** [comment]
If this is not what you expected, please share the expected generated .dot contents, so that I can have a better and clearer picture of what you would like.

**Comment by hhhapz** [comment]
The only reason it says 'booktest' there is because that's the name of the database/schema in PostgreSQL I ran it in. If you take a look at the _actual_ table names and columns, you will see that it is the schema you provided. The reason is that I just modified.

**Comment by suntong** [comment]
Ah, OK. Thanks a lot for your detailed explanation!
I'll double-check.
