### ISSUE TITLE
Proposal: Add overloaded stored procedures and functions to the same file

### ISSUE THREAD

**Issue by hhhapz** [xo/xo#286]
This change will make it so that overloaded procs will end up in the same file below each other. This change shouldn't be terribly difficult to implement, will just require changing the emitted file for the proc template to a []Proc, instead of just a single Proc, and then looping over them in the template. 

Perhaps there is a better way to implement this. 

This change will also make it easier to find procs, as with the current way overloaded procs are handled, the file names can get quite long as they contain the names of every parameter (or type) for each version, which may not be desirable. 

cc: @kenshaw

**Comment by kenshaw** [comment]
Not exactly sure what you mean here. You mean that `Procs => [][]Proc` or some such in the `types.Schema` struct?

**Comment by hhhapz** [comment]
The types package will not need to be changed, and this change will be specific to go templates (I should have mentioned this), as other languages (like Java) and the other templates (JSON, YAML) do not need to worry about multiple functions with the same name.
This change will purely change the data structure that is emitted within `gotpl.go` and The `proc.xo.go.tpl` template by emitting a `[]Proc` instead of a `Proc`. Where procs are emitted, https://github.com/xo/xo/blob/master/templates/gotpl/gotpl.go#L364, the `Data` provided in the `templates.Template` will be changed.
