### ISSUE TITLE
Enum from table query?

### ISSUE THREAD

**Issue by thnk2wn** [xo/xo#290]
I'd like to generate some Go enum-like code from PostgreSQL but using data from a custom query and not enums within PostgreSQL itself (differences in the id values etc.).

Is this a good use case for xo and if so how might I best go about that?

I started with custom template versions of the the `.tpl` files in `templates/gotpl/query` that blended in aspects of `templates/gotpl/schema/enum.xo.go.tpl`. I'm not seeing access to query row data for one

I'm really just looking for some DB codegen for lookup tables as "enums" / constants pretty much and not a full schema or data access logic.

**Comment by kenshaw** [comment]
@thnk2wn No, I don't believe `xo` is a good fit for your use case. Personally, for what you're describing, I'd use any number of other query tools (including the `psql` and `usql` command-line database clients)  with `awk`, `sed`, or some other post-processing tool. Alternately, depending on the complexity of the output needed, I would probably just craft a custom SQL query with the relevant code stanzas.

Think about it like this: `xo` is for working with database _metadata_, while `psql` or `usql` are better suited to working with the database's actual _data_.

**Comment by thnk2wn** [comment]
Thanks, that makes sense. I was thinking some of the metadata might be useful for generated comments and annotations and figured I might end up using some schema stuff later but for just lookup data not so much.
