### ISSUE TITLE
How are the models sources generated

### ISSUE THREAD

**Issue by suntong** [xo/xo#305]
The Go source code under `models/`, e.g., `column.xo.go`, `table.xo.go`, how are they generated please?

I checked but wasn't able to figure that out myself.

Thanks

**Comment by hhhapz** [comment]
The models are generated by running `go generate`. This runs `gen.sh` in the base directory of the repository. However, to run this, you will need to have all 5 databases running on your system and perhaps change the database connections appropriately at the top of the file. https://github.com/xo/xo/blob/master/gen.sh

**Comment by suntong** [comment]
Thanks!
