### ISSUE TITLE
MS SQL: Support schema please

### ISSUE THREAD

**Issue by suntong** [xo/xo#306]
MS SQL Server has a weird thing called schema, and in the AdventureWorksLT DB, everything is defined under this unusual schema (instead of the default `dbo`):

```sql
USE [AdventureWorksLT2017]
GO
/****** Object:  Schema [SalesLT]    Script Date: 8/11/2021 10:48:24 PM ******/
CREATE SCHEMA [SalesLT]
GO
```

As the result, when calling `xo schema "mssql://sqluser:xxx@localhost/SQLEXPRESS/AdventureWorksLT2017` on it, all that I got is:

![image](https://user-images.githubusercontent.com/422244/129131263-0109f852-e067-4a6d-9afe-b69658be5232.png)

Hope one day `xo` can support such unusual schema (instead of the default `dbo`), as more and more MS SQL Server based databases are using it, making `xo` reading from it will miss the majority of the tables. 

PS. 

The AdventureWorksLT2017 DB can be downloaded from https://docs.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-ver15&tabs=ssms, e.g., https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorksLT2017.bak

Or only get the DB structure from
https://gist.github.com/suntong/31bd261d9597ce1d1c12a966fffbca17

Thanks

**Comment by kenshaw** [comment]
@suntong yes, `xo` will work with a SQL Server schema. Please see the `_examples/init/sqlserver.sql` for a `usql` script that will create a database on SQL Server in a way that is friendly to `xo`:

```sh
$ cat init/sqlserver.sql 
EXEC sp_configure
  'contained database authentication', 1;

RECONFIGURE;

DROP LOGIN :NAME;

DROP DATABASE :NAME;

CREATE DATABASE :NAME
  CONTAINMENT=PARTIAL;

\connect 'ms://localhost/':NAME

CREATE LOGIN :NAME
  WITH
    PASSWORD=:'PASS',
    CHECK_POLICY=OFF,
    DEFAULT_DATABASE=:NAME;

CREATE USER :NAME
  FOR LOGIN :NAME
  WITH DEFAULT_SCHEMA=:NAME;

CREATE SCHEMA :NAME AUTHORIZATION :NAME;

EXEC sp_addrolemember 'db_owner', :'NAME';
```

If you need to work against an existing database, then I'd suggest trying the following:

1. Changing the default schema for the user you'll be using with `xo`
2. Changing the `db_owner` to the user you're using with `xo`
3. Checking the documentation for `github.com/denisenkom/go-mssqldb` to see if there are additional options that can be passed to set/force a schema. Any options should be usable with `xo` via standard URL query options -- ie, `opt1` and `opt2` in the following example: `sqlserver://user:pass@host/database?opt1=...&opt2=...`

Hope that helps, cheers.
