### ISSUE TITLE
Postgresql Update statement is broken for composite primary key

### ISSUE THREAD

**Issue by fho** [xo/xo#325]
Hello,

I'm using 
- xo version: 72728fa2f2c0704489f0280e75886481a2f78754 and
- postgresql version: 13.1.

When xo code is generated for a postgresql table that has a composite primary key, the generated update statement is broken.

In the generated where clause the primary keys are concatenated with an `, ` instead of ` AND `.

## How to reproduce:

1. Create the following table: 
```sql
create table users (firstname text, lastname text, a_number int, primary key(firstname, lastname));
```
2. Run `xo schema` to generate the code

### Result

The generated Update() method is:
```go
// Update updates a User in the database.
func (u *User) Update(ctx context.Context, db DB) error {
[...]
    const sqlstr = `UPDATE public.users SET ` + `a_number = $1 ` + `WHERE firstname = $2, lastname = $3`
[...]
}
```
The sqlstr query is broken. `WHERE firstname = $2, lastname = $3` is not valid psql syntax.
It should be instead:
```sql
UPDATE public.users SET ` + `a_number = $1 ` + `WHERE firstname = $2 AND lastname = $3
```

**Comment by hhhapz** [comment]
You are correct. Feel free to submit a PR (or otherwise let me know and I will do so) :)

**Comment by fho** [comment]
@hhhapz I created a PR  :-)
