### ISSUE TITLE
SQLite3 Issue with Parameters

### ISSUE THREAD

**Issue by joelholmes** [xo/xo#329]
The sqlite driver I'm using is the [same one](https://github.com/mattn/go-sqlite3) you have in your examples but the parameters expect '?' and not '$1'. I can't find an option or flag to set the generation tool to work that way. Am I missing something?

**Comment by hhhapz** [comment]
Hey, mattn/go-sqlite3 supports both parameters. The examples use $1, $2, $3... and all pass for me.

**Comment by kenshaw** [comment]
@joelholmes you might want to check which version of SQLite3 you're using. `xo` is currently using `github.com/mattn/go-sqlite3 v1.14.8`, which is the latest version I believe. Please note that `v1` is actually the most latest series of the `mattn/go-sqlite3` driver, as there was an accidental `v2` series tagged.

**Comment by joelholmes** [comment]
Sorry about the misunderstanding there. I realized that I think I'm having issues with the auto generated fields using ` sql.NullString`. I hard coded the string value and it works. My primary keys are strings (not int). Is there a flag that can help me with this?

**Comment by hhhapz** [comment]
@joelholmes sqlite3 has this (in my opinion, very weird) quirk that primary keys can be null. Try specifying `NOT NULL` in your schema and see if it works, i.e `col_name TEXT PRIMARY KEY NOT NULL`

**Comment by joelholmes** [comment]
Yeah that worked. I assumed that the primary key would enforce the not null. Thank you for the guidance!

**Comment by hhhapz** [comment]
Just as something to keep note of, nullables are enforced in strict mode for primary key, might be something you want to look into for production :) https://sqlite.org/src/wiki?name=StrictMode
