### ISSUE TITLE
Example of adding a struct tag? 

### ISSUE THREAD

**Issue by richp10** [xo/xo#330]
Generated go code looks like this: 

```
type User struct {
	ID                     int            `json:"id" `     // id
```

And I want an additional struct tag like this - with 'db' 

```
type User struct {
	ID                     int            `json:"id" db:"id" `    
```

I thought it could be done with --go-field-tag - but cannot work out the notation

**Comment by hhhapz** [comment]
Hey, @richp10 , the field tag uses go template syntax. Here is the default value:
```
"`json:\"{{ .SQLName }}\"`"
```

**Comment by richp10** [comment]
Worked - huge thanks for the great project...
