### ISSUE TITLE
doesn't work with sqlite

### ISSUE THREAD

**Issue by cooperspencer** [xo/xo#338]
I am trying to run `xo query 'file:mydb.db?loc=auto' -o models` but nothing happens.

**Comment by kenshaw** [comment]
@cooperspencer Assuming you built `xo` from source? Is this an existing (possibly older?) database, if so, would it be possible to share it? Were there any error messages, or just nothing happened? Could you share more information about what OS/Architecture you're trying to use `xo` on?

**Comment by newbeelearn** [comment]
I use following command for query generation in sqlite. 
xo query sq:$DB -o $MODELSDIR -M -B -2 -T $qname < "$SQLDIR/queries/$qname.sql"
replace $ with db/models directory etc.

I am not sure if queries can be generated like this for sqlite as it does not support stored procedure afaik.

**Comment by cooperspencer** [comment]
@kenshaw I installed it with `go install github.com/xo/xo`.
I am ran it on Linux (EndeavourOS). This is my system info:
```bash
❯ inxi
CPU: quad core 11th Gen Intel Core i7-1165G7 (-MT MCP-)
speed/min/max: 1079/400/4700 MHz Kernel: 5.15.12-arch1-1 x86_64 Up: 1m
Mem: 2248.3/15796.7 MiB (14.2%) Storage: 465.76 GiB (25.7% used) Procs: 272
Shell: Zsh inxi: 3.3.11
❯ sqlite3 --version
3.37.1 2021-12-30 15:30:28 378629bf2ea546f73eee84063c5358439a12f7300e433f18c9e1bddd948dalt1
```
My database is quite simple:
```sql
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "commands" (
	"id"	INTEGER UNIQUE,
	"command"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "paths" (
	"id"	INTEGER UNIQUE,
	"path"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "history" (
	"id"	INTEGER UNIQUE,
	"timestamp"	INTEGER NOT NULL,
	"command_id"	INTEGER,
	"path_id"	INTEGER,
	FOREIGN KEY("command_id") REFERENCES "command"("id"),
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("path_id") REFERENCES "paths"("id")
);
COMMIT;
```

**Comment by hhhapz** [comment]
you need to use `xo schema` not `xo query`

**Comment by cooperspencer** [comment]
ahh... that helped. I still get an error, but that's probably because of my DB design.

**Comment by hhhapz** [comment]
If you post the error, maybe we can hlep you out :)

**Comment by cooperspencer** [comment]
```bash
xo schema sqlite3:chronicler.db
error: could not find field, refTable, or refField for table "history" foreign key ""
```

**Comment by hhhapz** [comment]
your foreign key is referencing table `command` instead of table `commands` in your `history` table.

**Comment by hhhapz** [comment]
As an aside, I suggest turning on the pragma to properly enforce foreign keys in your database, to catch these errors on schema creation instead of debugging it later on: `PRAGMA foreign_keys = ON;`

**Comment by cooperspencer** [comment]
@hhhapz it is working now. thanks for the help :smile:
