### ISSUE TITLE
Go field tags seem to no longer work

### ISSUE THREAD

**Issue by localrivet** [xo/xo#352]
I just updated to your latest version. It's been a couple of months and I thought I needed to update however it now fails when using `--go-field-tags` with this code (which worked before I updated):

```sh
xo schema ${POSTGRES_DSN} \
	--go-field-tag='`json:"{{ .SQLName }}" db:"{{ .SQLName }}"`' \
	-o ./internal/models \
	-e *.created_at \
	-e *.updated_at \
	-e *.deleted_at \
	-k smart
```

Here's the error produced:

```sh
error: productproperty.xo.go:24:20: expected ';', found json (and 5 more errors)
error: 1 errors encountered
```

If I remove the `--go-field-tags` option it works.

Adding the verbose tag didn't tell me anything.

Let me know if you need any more information.

Thanks! Great project!!

**Comment by localrivet** [comment]
I figured out the problem.

At some point backticks were added to the template by default.
If found this in `templates/go.go` on line 1856 

```go
func (f *Funcs) field(field Field) (string, error) {
	buf := new(bytes.Buffer)
	if err := f.fieldtag.Funcs(f.FuncMap()).Execute(buf, field); err != nil {
		return "", err
	}
	var tag string
	if s := buf.String(); s != "" {
		tag = " `" + s + "`" // <<<<< ---- HERE
	}
	return fmt.Sprintf("\t%s %s%s // %s", field.GoName, f.typefn(field.Type), tag, field.SQLName), nil
}
```

By removing the backticks (that once were needed) it now works as expected. 

```sh
xo schema ${POSTGRES_DSN} \
	--go-field-tag='json:"{{ .SQLName }}" db:"{{ .SQLName }}"' \
	-o ./internal/models \
	-e *.created_at \
	-e *.updated_at \
	-e *.deleted_at \
	-k smart
```

**Comment by hhhapz** [comment]
Hey, thanks for pointing this out. This was actually unintionally breaking compatibility with what the code should have been like. During the latest refactor, we accidentally moved the back quotes out of the default value, which caused me to fix the issue in the wrong place. I think it might be worth to revert this functionality. Let me know if that's okay with you.
