### ISSUE TITLE
BPMN

### ISSUE THREAD

**Issue by timdadd** [xo/xo#372]
Is there a place in the templates to add custom initialisms during initialisation?  I would like my table PROCESS_BPMN to be ProcessBPMN in GO but it comes out as ProcessBpmn.
Great product for those more RDBMS founded.
Thanks,
Tim

**Comment by kenshaw** [comment]
```sh
$ xo schema --go-initialism BPMN
```
Look at the `_examples/booktest/gen.sh` if you'd like to see it done in an actual project.
