### ISSUE TITLE
Could you add the Comment of each Field of migration table to generated xo files ?

### ISSUE THREAD

**Issue by kmtszky** [xo/xo#374]
**Could you add the Comment of each Field of migration table to generated xo files?**

I appreciate your valuable efforts.

I am not good at writing English and sorry if my English is wrong.
If you couldn't understand what I mean, please let me know.

I would like to talk about this file: https://github.com/xo/xo/blob/master/templates/go/go.go

The Field structure has Comment like bellow, but the Comment is always empty.
```golang
// Field is a field template.
type Field struct {
	GoName     string
	SQLName    string
	Type       string
	Zero       string
	IsPrimary  bool
	IsSequence bool
	Comment    string
}
```

I guess this is caused by method named "convertField" (bellow).
As you can see, returned Field's Comment is empty because xo.Field structure doesn't have Comment.
(if it had Comment, "Comment: f.Comment" could be added to the returned Field)
```golang
func convertField(ctx context.Context, tf transformFunc, f xo.Field) (Field, error) {
	typ, zero, err := goType(ctx, f.Type)
	if err != nil {
		return Field{}, err
	}
	return Field{
		Type:       typ,
		GoName:     tf(f.Name),
		SQLName:    f.Name,
		Zero:       zero,
		IsPrimary:  f.IsPrimary,
		IsSequence: f.IsSequence,
	}, nil
}
```

**Comment by evassilyev** [comment]
@kmtszky hi!
I need the same functionality, but it required more changes than only fix the templates.
Here's my PR to implement it:
[https://github.com/xo/xo/pull/377](https://github.com/xo/xo/pull/377)

@kenshaw please, take a look.

**Comment by kmtszky** [comment]
@evassilyev hi!
Thank you for your quick response. It is very much appreciated !

I'm terribly sorry but I have one more request.
Could you also make changes for MySQL in addition?
The https://github.com/xo/xo/pull/377 PR seems to support only PostgreSQL but we would like to use xo for MySQL.

**Comment by evassilyev** [comment]
@kmtszky done.
Comments of the table fields will be extracted for MySQL too.
The changes in the latest commit of the PR.

**Comment by kmtszky** [comment]
@evassilyev 
Thank you very much for your cooperation.
I'm looking forward to your PR being merged.

**Comment by evassilyev** [comment]
@kmtszky the changes were merged into xo master. You should set this issue as closed.

**Comment by kmtszky** [comment]
@evassilyev 
I am sorry for closing this issue late. 
Thank you for your contacting and kind cooperation!
