### ISSUE TITLE
error: createdb: unable to import package: 1:22: import "createdb" error: unable to find source related to: "createdb"

### ISSUE THREAD

**Issue by bigBron** [xo/xo#381]
os windows 11 home 21H2
go version go1.19.2 windows/amd64
[ox current latest version](https://github.com/xo/xo/commit/837398a92407cc9524a4390754f001131047e42a)
[compile the source code using build-release.sh](https://github.com/xo/xo/blob/e4617dc4c53fe1fc0e7fa8fc54df6f9bb621c76a/build-release.sh)
The xo command cannot be executed, and get error message: error: createdb: unable to import package: 1:22: import "createdb" error: unable to find source related to: "createdb"

**Comment by kenshaw** [comment]
We don't actually use the `build-release.sh` script, and that was copied over from sister project `usql`.

**Comment by bigBron** [comment]
It is also wrong to clone the source code to go build without using build-release.sh. or use go install also wrong
I upgraded the go version to 1.19.4 and it didn't work either. did any of the steps go wrong?

**Comment by bigBron** [comment]
I just want to try this project, but it is too difficult to install. I don't know the reason. Normally, many projects can be used directly by going install

**Comment by bigBron** [comment]
I tried to use another win10 computer to install the same problem😥😥

**Comment by bigBron** [comment]
I tried to checkout to different historical versions for build, and randomly tested the latest versions they don't work, but the version [2021/7/29 7:51](https://github.com/xo/xo/commit/ced03825d73715e150dae08ff35c5526a4dc2ae8) can be successfully executed, indicating that there is something wrong with the latest code
