### ISSUE TITLE
Custom types... again 

### ISSUE THREAD

**Issue by jwc-clinnection** [xo/xo#399]
What is the idiomatic xo way to define custom types in xo? Create a custom "loader"? 
```
func goType(ctx context.Context, typ xo.Type) (string, string, error) {
	driver, _, schema := xo.DriverDbSchema(ctx)
	var f func(xo.Type, string, string, string) (string, string, error)
	switch driver {
	case "mysql":
		f = loader.MysqlGoType
	case "oracle":
		f = loader.OracleGoType
	case "postgres":
		switch mode := ArrayMode(ctx); mode {
		case "stdlib":
			f = loader.StdlibPostgresGoType
		case "pq", "":
			f = loader.PQPostgresGoType
		default:
			return "", "", fmt.Errorf("unknown array mode: %q", mode)
		}
	case "sqlite3":
		f = loader.Sqlite3GoType
	case "sqlserver":
		f = loader.SqlserverGoType
	default:
		return "", "", fmt.Errorf("unknown driver %q", driver)
	}
	return f(typ, schema, Int32(ctx), Uint32(ctx))
}
```

**Comment by jwc-clinnection** [comment]
It seems that copying and pasting "PQPostgresGoType" from the loader package into go.go will do the trick.

**Comment by kenshaw** [comment]
@jwc-clinnection the way I would do this, is the following:

1. In the project where `xo` is being used, create a directory: `mkdir mytemplate`
2. Dump the Go template using `xo dump mytemplate`
3. Edit the templates that are created in the `mytemplate` folder, adding a `{{ if ... }} {{ else if ... }} {{ else }} {{ end }}` for the types you want to map, or a higher level Go `func` that is exposed to the template
4. Test the template using `xo query -d mytemplate` or `xo schema -d mytemplate`
5.  Add the requisite `xo ...` call to a code generation step in CI scripts (or something like a `Makefile`) for the `xo` call(s)
6. Add/commit the custom `mytemplate` directory to the project
7. Optionally pin the version of `xo` used in the project
