### ISSUE TITLE
The options listed in README.md does not work on latest version(v1.0.2)

### ISSUE THREAD

**Issue by kazuo-mu** [xo/xo#410]
Hello. I'm using xo in our project. I have a question.
I installed xo latest version by using go install and homebrew.

I tried the option `--help-long` but it doesn't work (I actually want to use the option `--go-enum-table-prefix`). 
```
$ xo --version
xo 1.0.2

$ xo --help-long
error: unknown flag: --help-long
```

And also I am concerned that version on my display is `v0.0.0.dev` when I install latest version by go install.

I would be happy to get a reply.

[my environment]
- Apple M3
- go version go1.22.4 darwin/arm64

**Comment by kazuo-mu** [comment]
I understand --go-enum-table-prefix is not supported.

**Comment by kazuo-mu** [comment]
How do I do if enum type name are conflict over DB tables?

**Comment by evassilyev** [comment]
@kazuo-mu there's outdated set of actual flags.
For `--go-enum-table-prefix` try to use `--xo-enum-table-prefix`

**Comment by evassilyev** [comment]
@kazuo-mu actually, in `--go-enum-table-prefix` and `--xo-enum-table-prefix` - first world (**go** or **xo** in the example) must be the same as the name of directory where you store your templates. And use **go** in case of default templates.

**Comment by kazuo-mu** [comment]
@evassilyev 
Thank you for replying. After I dumped the templates into ./templates/go directory, I run the following command. 
The result is that option is not found.

```
$ xo schema mysql://user:password@localhost/sample_db --src ./templates/go --go-enum-table-prefix
error: unknown flag: --go-enum-table-prefix
```

**Comment by kazuo-mu** [comment]
What can I do if enum type field names are conflict over DB tables?

**Comment by evassilyev** [comment]
@kazuo-mu if you use **--go-*** prefixes do not specify **--src** at all. It works only with not dumped default xo templates, that stored inside the binary. May be I'm not 100% right.
But the trick is that according to sources **--go-***  like commands has dynamical naming based on the templates.
Just try two cases:
1. Do not dump template and use **--go-***
2. Dump template to the folder named **xo**, and set **--xo-***

**Comment by kazuo-mu** [comment]
@evassilyev Thank you for your advises. I tried two cases, but --*-enum-table-prefix option was not found. I think the option was deleted.
I dealt with the problem (that enum column names are conflict) by a temporary approach. 
I created enum type files manually by copying a type file automatically generated by `xo scheme` command.

I will stop dealing with the problem for a while. Thank you!
