### ISSUE TITLE
Comment support

### ISSUE THREAD

**Issue by kaleworsley** [xo/xo#44]
Hey @kenshaw. I'm keen to add support for Postgres comments on tables and columns etc. I see the readme has

> Finish COMMENT support for PostgreSQL/MySQL and update templates accordingly.

but I can't find any the existing work on the feature.

Has this been started? If not, I'd like to take a crack at it if you're happy to look at a PR for this.

Thanks for the great tool!

**Comment by kenshaw** [comment]
I have partial support that is nowhere near completed for PostgreSQL. However, any implementation I would like for multiple databases to be supported. I don't know if Oracle/MSSQL support comments, but I believe MySQL does. Additionally, for SQLite, I'd like to extract comments from the schema if possible (likely using regular expressions or some such).

My original thought was that I was going to use the comments on tables/columns/etc. as a way to hold metadata for schema directives to xo, but realize this may not be elegant/confusing.

I'm more than happy to consider any pull request that is well written, so please send one if you have it. 

A quick overview of what would need to be done:
Fields would need to be added to the different template struct types in `internal/types.go`. It's there that you should add a `Comment string` member to the struct (if not already defined), and then modify the files in `templates/` to support/output those. Additionally, you'll need to modify various database support files in `loaders/` to extract the comments for the types. Lastly, you'll need to add the call in `xo.go` and modify the logic in `internal/loader.go` to support the changed loader code.

**Comment by stub42** [comment]
I have two, potentially conflicting, use cases for this. 

1) Specify capitalization, so my alllowercase tablenames and functionnames are correctly CamelCased.
2) Have the comments inserted as comments, so my database comments propagate to my godoc documentation.

**Comment by olegsu** [comment]
@kenshaw is camel case columns not supported?

**Comment by kenshaw** [comment]
@olegsu camel case columns should be supported. Is there a reason you're adding this on a very old and closed ticket?
