### ISSUE TITLE
generated postgres json datatype undefined

### ISSUE THREAD

**Issue by phamdt** [xo/xo#59]
i generated a model from a postgres db. the struct had a line that looked similar to this:
`MyColumnText      JSON           `json:"my_column_text"`       // my_column_text`

but when building the application `JSON` was undefined. is there an expectation that i would have already handled this type on my own or am i missing something with regard to using xo?

**Comment by kenshaw** [comment]
I'm not sure if I'm going to introduce JSON support for postgres or not. I would like to, but unless there is underlying support for JSON types by the native / underlying database driver, I'm not sure it is feasible at this time to support it. I'm in the process of completely rewriting xo to be support much more flexible types (and to be more generic than it currently is). If you could share a real world schema using JSON with me, I would take how you're using it into consideration and might be able to support JSON.

As it is, none of the production schemas I've worked with in "real world" scenarios use JSON, so it is difficult for me to come at it from a usability perspective.

**Comment by phamdt** [comment]
ah, so i need to handle it on my own. gotcha.

as far as example usage, i use it when i want to provide various options to the user in which the stored data is semistructured and/or arbitrary on one table. one scenario would be storing various fields that represent css rules allowing a user to configure what ends up being a stylesheet rendered in some UI. some possible representations:
```
{
  title_font: 'Arial',
  title_size: '14px',
  ...
}
```
```
{
  CUSTOM_SELECTOR: {
    WHATEVER_PROPERTY: WHATEVER_VALUE,
    ANOTHER_PROPERTY: ANOTHER_VALUE
  },
  ...
}
```
with just a few fields, i might have accepted giving any of those properties its own dedicated column. however, with numerous properties i have to accept various sparse rows, limiting myself (and therefore the user) to properties explicitly added to the table, and/or doing more joins than i'd like.

**Comment by wayneashleyberry** [comment]
I ran into this the other day with MySQL and was wondering if we could not use the `json.RawMessage` type here?

**Comment by lukasreichart** [comment]
are there any plans to support the json data type in the future? Depending on what exactly would be needed I could also contribute to the feature.
