### ISSUE TITLE
Missing functions for tables using inheritance (postgresql)

### ISSUE THREAD

**Issue by nsjph** [xo/xo#64]
I've only tested this with PostgreSQL (9.5), so I don't know if this affects other DBs.

When I have a schema of:

CREATE TABLE parent (
id SERIAL PRIMARY KEY,
name TEXT NOT NULL);

CREATE TABLE child (
blah TEXT;
) INHERITS (parent);

When using xo to generate code, it generates Insert/Update/Delete/Upsert/etc functions for "parent" table, but not for "child" table. Is there a way to force this? At the moment, I have to copy, paste and modify the parent functions to use in child.xo.go

**Comment by kenshaw** [comment]
Yes, I did not originally intend xo to be used with complicated schemas that are not supported by at least 2 or more databases. I will look into creating a fix for this during the large xo rewrites that will be happening soon. For reference, I believe the most "idiomatic" way to do this in Go would be to have the generated type for the child include the parent type, along these lines:

```go
type Parent struct {
  A string
}

type Child struct {
  Parent
  B string
}
```

To get this working I really need a real world schema to work with. There are likely so many problems that I foresee might be encountered with the introspection code that it's likely not worth fixing if I don't have a real world example to test against. 

FWIW, I would suggest **NOT** using table inheritance in your schemas. While the concept of table inheritance is nice, "in practice" I've rarely ever seen them used to any real effect. And my experience is that developers will down the road want to change the parent to a different database table, which in turn devolves into a big mess.

I would just suggest copying/pasting the rows into the child table's schema definition when they're needed. And, as far as I'm aware, there's no performance benefit  to actually using inherits clauses in a schema, and the inherits clause is simply there as a notation helper for database architects (but it doesn't actually "do" anything). Also, from my experience when using inherits clauses with databases, there has never been a time that I wanted "only" the parent data, nor have I ever seen "multiple" table hierarchies being used in real practice. 

I'm happy to be proven wrong, however -- if you have an example of an in-use schema where table inheritance is absolutely necessary (and not just for syntax shorthand) feel free to share here or email me directly if it contains sensitive information that cannot be made public. My email can be obtained through either my GitHub profile or by looking at the commit logs.

**Comment by nsjph** [comment]
In this instance, I've opted to move away from inheritance. Thanks for the detailed reply.
