### ISSUE TITLE
Generate models (structs) only?

### ISSUE THREAD

**Issue by tlianza** [xo/xo#68]
Is there a way to just generate structs and skip all of the CRUD functions?

**Comment by kenshaw** [comment]
No -- this would be a relatively simple option to add, however. Additionally, it is fairly straight forward to create your own templates and use them with xo that do not generate any funcs (just comment them out). That said, I would be willing to add a PR for adding this option, as it is likely useful to others.

**Comment by tlianza** [comment]
Thx... I'm playing with customizing templates now and I think that's the best solution for my particular use case, since I would love to tweak the output in other ways. Realized I could do that only after a bit more reading.
