### ISSUE TITLE
Support UUID types (uuid-ossp, pgcrypto)

### ISSUE THREAD

**Issue by jcramb** [xo/xo#74]
My project uses pgcrypto for handling UUID types as primary keys. 

    CREATE EXTENSION pgcrypto;
    CREATE TABLE clients (
        client_id uuid PRIMARY KEY DEFAULT gen_random_uuid()
    );

The resulting XO generated code fails to compile with an "undefined: UUID" error. The file 'examples/pgcatalog/pgtypes/types.go' has UUID defined as a struct{}, but there's a google UUID implementation (https://github.com/google/uuid) that could be used if needed.

Are UUID types intended to be supported by XO and if not do you have any recommendations on the best way to handle this?

**Comment by kyleterry** [comment]
I'm currently trying to do this too and I'm looking for a work-around using the templates. I'll let you know if I find one. It would be nice if it just auto-detected the UUID type and imported the google package.
