### ISSUE TITLE
Only getting the structure

### ISSUE THREAD

**Issue by tgirgin23** [xo/xo#82]
Hi there,

Thank you for making this package! I am currently using the latest version of go (1.8), trying to generate some go code for my postgres database (9.6). I have used your tool a few weeks ago without any problems, however I have not been able to get anything but the structure of my tables (See below) more recently. Here the the command line that I executed:

xo "pgsql://username:pass@ip/db?sslmode=disable" -M -B -s public -o models -v

Do you have any idea on what could be causing this issue?

Thank you.
Tim 

```
// Package models2 contains the types for schema 'public'.
package models2

// GENERATED BY XO. DO NOT EDIT.

import (
	"time"
)

// User represents a row from 'public.users'.
type User struct {
	ID            int        `json:"id"`             // id
	Username      string     `json:"username"`       // username
	TwitterHandle string     `json:"twitter_handle"` // twitter_handle
	JoinedOn      *time.Time `json:"joined_on"`      // joined_on
	AddCount      int        `json:"add_count"`      // add_count
	EditCount     int        `json:"edit_count"`     // edit_count
}
```

**Comment by turnkey-commerce** [comment]
Tim, I've seen this on occasion related to issues with the primary key, could you please share your SQL used to generate the table for reproduction?
